### ISSUE TITLE
Error when trying to launch 

### ISSUE THREAD

**Issue by jake69mac** [unused/airstream#26]
I keep getting this error when i try to launch it any ideas on how to fix it?

```/Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:29:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:29:in `open'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:29:in `block in connect'
	from /Users/jakemcallister/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
	from /Users/jakemcallister/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:29:in `connect'
	from /Users/jakemcallister/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
	from /Users/jakemcallister/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:750:in `start'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airplay-0.2.9/lib/airplay/protocol.rb:47:in `make_request'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airplay-0.2.9/lib/airplay/protocol.rb:28:in `post'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airplay-0.2.9/lib/airplay/protocol/media.rb:37:in `play'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airplay-0.2.9/lib/airplay/protocol/media.rb:29:in `send'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airplay-0.2.9/lib/airplay/client.rb:41:in `send_video'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/lib/airstream/device.rb:32:in `video='
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/lib/airstream/device.rb:14:in `file='
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/lib/airstream/player.rb:25:in `current_file='
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/lib/airstream/player.rb:21:in `play'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/lib/airstream/player.rb:9:in `initialize'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/bin/airstream:93:in `new'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/gems/airstream-0.4.7/bin/airstream:93:in `<top (required)>'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/bin/airstream:23:in `load'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/bin/airstream:23:in `<main>'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jakemcallister/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by jake69mac** [comment]
Hi @unused  I got it sorted in the end
