### ISSUE TITLE
Live stream error

### ISSUE THREAD

**Issue by dejl** [unused/airstream#31]
When trying to live stream, it works but quickly exits with an error:

var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progressable.rb:82:
in `validate_progress': You can't set the item's current value to be greater than the total. (R
untimeError)
        from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progre
ssable.rb:45:in `progress='
        from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:131:in `w
ith_progressables'
        from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in `bl
ock in progress='
        from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:147:in `w
ith_update'
        from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in `pr
ogress='
        from /var/lib/gems/1.9.1/gems/airstream-0.4.7/bin/airstream:102:in `<top (required)>'
        from /usr/local/bin/airstream:23:in `load'
Me@Server:~$ /local/bin/airstream:23:in `<main>'

**Comment by dejl** [comment]
97c97
<   pbar = ProgressBar.create({ format: '%t |%b%i| %p%%', total: player.duration })
---
>   #pbar = ProgressBar.create({ format: '%t |%b%i| %p%%', total: player.duration })
101,102c101,102
<     pbar.title = "#{player.current_title} #{formatted_time}"
<     pbar.progress = player.elapsed_time
---
>    # pbar.title = "#{player.current_title} #{formatted_time}"
>     #pbar.progress = player.elapsed_time
105,106c105,106
<   end until io.quit? || player.finished?
<   pbar.finish
---
>   end until io.quit? #|| player.finished?
> # pbar.finish
