### ISSUE TITLE
"too many connection resets"  when +30s or -30s

### ISSUE THREAD

**Issue by jrevillard** [unused/airstream#35]
Here is the stack when I press . or , on a video:

```
loading can take a few seconds...
=> press [q] to exit airstream
/usr/lib64/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': too many connection resets (due to end of file reached - EOFError) after 139 requests on 21788540, last used 0.003299031 seconds ago (Net::HTTP::Persistent::Error)
	from /usr/lib64/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
	from /usr/lib64/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /usr/lib64/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /usr/lib64/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /usr/lib64/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /usr/lib64/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
	from /usr/lib64/ruby/2.1.0/net/http.rb:1411:in `catch'
	from /usr/lib64/ruby/2.1.0/net/http.rb:1411:in `transport_request'
	from /usr/lib64/ruby/2.1.0/net/http.rb:1384:in `request'
	from /home/jerome/.gem/ruby/2.1.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:999:in `request'
	from /home/jerome/.gem/ruby/2.1.0/gems/airplay-0.2.9/lib/airplay/protocol.rb:47:in `make_request'
	from /home/jerome/.gem/ruby/2.1.0/gems/airplay-0.2.9/lib/airplay/protocol.rb:28:in `post'
	from /home/jerome/.gem/ruby/2.1.0/gems/airplay-0.2.9/lib/airplay/protocol/scrub.rb:32:in `to'
	from /home/jerome/.gem/ruby/2.1.0/gems/airplay-0.2.9/lib/airplay/protocol/media.rb:46:in `scrub'
	from /home/jerome/airstream/lib/airstream/device.rb:45:in `scrub'
	from /home/jerome/airstream/lib/airstream/player.rb:49:in `seek'
	from /home/jerome/airstream/lib/airstream/player.rb:38:in `update'
	from /home/jerome/airstream/bin/airstream:104:in `<top (required)>'
	from /home/jerome/.gem/ruby/2.1.0/bin/airstream:23:in `load'
	from /home/jerome/.gem/ruby/2.1.0/bin/airstream:23:in `<main>'
```

Best.

**Comment by unused** [comment]
Ahoi - do you receive this any time? Can you give me some details on your environment (operating system used etc.)?

**Comment by jrevillard** [comment]
Hi,

Yes, I have this all the time. I'm running on Gentoo x86_64:

```
[jerome:/home/jerome/airplay/airstream] master ± ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
[jerome:/home/jerome/airplay/airstream] master ± bundle list
Gems included by the bundle:
  * airplay (0.2.9)
  * airstream (0.4.9)
  * aruba (0.6.2)
  * builder (3.2.2)
  * bundler (1.10.6)
  * childprocess (0.5.5)
  * colored (1.2)
  * coveralls (0.7.11)
  * cucumber (1.3.19)
  * diff-lcs (1.2.5)
  * dnssd (2.0.1)
  * docile (1.1.5)
  * ffi (1.9.8)
  * gherkin (2.12.2)
  * mime-types (2.4.3)
  * minitest (5.5.1)
  * multi_json (1.11.0)
  * multi_test (0.1.2)
  * net-http-digest_auth (1.4)
  * net-http-persistent (2.9.4)
  * netrc (0.10.3)
  * oj (2.12.1)
  * rack (1.5.5)
  * rake (10.4.2)
  * rake-notes (0.2.0)
  * rest-client (1.7.3)
  * rspec-expectations (3.2.0)
  * rspec-support (3.2.2)
  * ruby-progressbar (1.1.1)
  * simplecov (0.9.2)
  * simplecov-html (0.9.0)
  * term-ansicolor (1.3.0)
  * thor (0.19.1)
  * tins (1.3.5)
  * webrick (1.3.1)
```
Best,
Jerome
