### ISSUE TITLE
Airplay does not work with live streams

### ISSUE THREAD

**Issue by mdreier** [unused/airstream#41]
When watching a live stream (e.g. from Twitch) the application shows two errors:

1. The application crashes with an error related to the progress bar.
2. The application exits directly.

Both errors seem to be caused by the fact that a live stream has a _negative duration_.

Here is the stack trace for the first error:

```
loading can take a few seconds...
=> press [q] to exit airstream
Progress |================================================================| 100%
/var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/bar.rb:29:in `*': negative argument (ArgumentError)
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/bar.rb:29:in `standard_complete_string'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/formatter.rb:72:in `bar'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/format/base.rb:26:in `block in process'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/format/base.rb:25:in `each'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/format/base.rb:25:in `process'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/formatter.rb:15:in `format'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:112:in `to_s'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:160:in `block in update'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/throttle.rb:12:in `choke'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:154:in `update'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:148:in `with_update'
	from /var/lib/gems/2.3.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:95:in `title='
	from /var/lib/gems/2.3.0/gems/airstream-0.4.10/bin/airstream:102:in `<top (required)>'
	from /usr/local/bin/airstream:23:in `load'
	from /usr/local/bin/airstream:23:in `<main>'
```

I was able to work around the errors by removing the progress bar and disabling the exiting when the player is finished, but this is of course only a dirty hack. I'll try to look into the issue more and maybe provide a better fix, but I wanted to get the bug report out there.

**Comment by unused** [comment]
Thx a lot for the input, I will have a look asap.
