### ISSUE TITLE
Installation failed in Debian 8.7 Jessie

### ISSUE THREAD

**Issue by PETR4** [unused/airstream#42]
Hi, I just installed the Debian 8.7 Jessie and try to install the airstream, already installed the packages: `ruby-dev` and `libavahi-compat-libdnssd-dev.`

I got these error messages:

```
root@debian:/home/user/Downloads/airstream# gem install airstream
Building native extensions.  This could take a while...
ERROR:  Error installing airstream:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking for dns_sd.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--with-warnings
	--without-warnings
	--with-dnssd-dir
	--without-dnssd-dir
	--with-dnssd-include
	--without-dnssd-include=${dnssd-dir}/include
	--with-dnssd-lib
	--without-dnssd-lib=${dnssd-dir}/lib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
	from /usr/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
	from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from /usr/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/dnssd-2.0.1 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/dnssd-2.0.1/gem_make.out
```

I believe that something package is missing on my brand new system.

I am glad any tip.

**Comment by mifix** [comment]
Hey,

further down of your error log, you have:

> /usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.


This means your system is missing a compiler to compile native gems. Just run 

`sudo apt-get install build-essential`

and you're good to go.

**Comment by PETR4** [comment]
Thanks!

You're right!
