### ISSUE TITLE
Can't handle  `scrub': undefined method `scrub' for nil:NilClass (NoMethodErro

### ISSUE THREAD

**Issue by jimisan** [unused/airstream#43]
airstream -o 172.80.255.19
loading can take a few seconds...
=> press [q] to exit airstream
/home/satori/.gem/ruby/2.4.0/gems/airstream-0.4.10/lib/airstream/device.rb:45:in `scrub': undefined method `scrub' for nil:NilClass (NoMethodError)
	from /home/satori/.gem/ruby/2.4.0/gems/airstream-0.4.10/lib/airstream/device.rb:49:in `duration'
	from /home/satori/.gem/ruby/2.4.0/gems/airstream-0.4.10/lib/airstream/player.rb:88:in `duration'
	from /home/satori/.gem/ruby/2.4.0/gems/airstream-0.4.10/bin/airstream:97:in `<top (required)>'
	from /home/satori/.gem/ruby/2.4.0/bin/airstream:22:in `load'
	from /home/satori/.gem/ruby/2.4.0/bin/airstream:22:in `<main>'

**Comment by Raineer** [comment]
I also have this as well on
Linux monolithTower 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

michael@monolithTower ~/Pictures $ airstream -o 192.168.1.36 
loading can take a few seconds...
=> press [q] to exit airstream
/var/lib/gems/2.3.0/gems/airstream-0.4.10/bin/airstream:101:in `at': can't convert nil into an exact number (TypeError)                                                                                                                                     | 0%
	from /var/lib/gems/2.3.0/gems/airstream-0.4.10/bin/airstream:101:in `<top (required)>'
	from /usr/local/bin/airstream:23:in `load'
	from /usr/local/bin/airstream:23:in `<main>'
michael@monolithTower ~/Pictures $
